platform :ios, '11.0'

use_frameworks!

target '${POD_DEMO_APP}' do

  pod '${POD_NAME}Interface', :path => './../../${POD_NAME}Interface/'
  pod '${POD_NAME}', :path => '../'

  target '${POD_DEMO_APP}Tests' do
    inherit! :search_paths

    pod '${POD_NAME}', :path => '../', :testspecs => ['Tests']
  end
end