platform :ios, '11.0'

$modules_path = '../../../../'

$core_path = $modules_path + 'Core/'
$features_path = $modules_path + 'Features/'
$shared_path = $modules_path + 'Shared/'
$tests_path = $modules_path + 'Tests/'

use_frameworks!

target '${POD_DEMO_APP}' do

  pod '${POD_NAME}Interface', :path => './../../${POD_NAME}Interface/'
  pod '${POD_NAME}', :path => '../'

  target '${POD_DEMO_APP}Tests' do
    inherit! :search_paths

    pod '${POD_NAME}', :path => '../', :testspecs => ['Tests']
    #pod 'MPayTestUtils/Core', :path => '../../../../Tests/MPayTestUtils'
  end
end
