disabled_rules:
  - superfluous_disable_command
  - function_parameter_count
  - cyclomatic_complexity
  - identifier_name
  - large_tuple
  - line_length
  - file_length
  - nesting
  - opening_brace
opt_in_rules:
  - anyobject_protocol
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_string
  - file_header
  - file_name
  - implicitly_unwrapped_optional
  - legacy_random
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - static_operator
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
todo: warning
included:
  - ../Sources
excluded:
  - ../../../*/*/Example
  - ../../../*/*/*/Example
  - Pods
  - ${POD_DEMO_APP}
  - Tests
