platform :ios, '11.0'

$modules_path = '../../../'

$core_app_path = $modules_path + 'CoreApp/'
$features_path = $modules_path + 'Features/'
$shared_path = $modules_path + 'Shared/'
$tests_path = $modules_path + 'Tests/'

use_frameworks!

def external_pods
  pod 'Cartography'
  pod 'Kingfisher'
  pod 'SwiftGen'
  pod 'SwiftLint'
  pod 'lottie-ios'
end

def core_app
end

def shareds
  pod '${POD_NAME}', :path => $shared_path + '${POD_NAME}'
end

def ui_modules
end

def shareds_testspec
  pod '${POD_NAME}', :path => $shared_path + '${POD_NAME}', :testspecs => ['Tests']
end

target '${POD_DEMO_APP}' do
  external_pods
  core_app
  shareds
  ui_modules

  target '${POD_DEMO_APP}Tests' do
    inherit! :search_paths

    shareds_testspec
  end
end
